networks:
  peci_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1

services:
  # Base de Dados
  db:
    image: postgres:16-alpine
    container_name: peci_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      peci_network:
        ipv4_address: 172.20.0.10

  #Backend
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        HF_TOKEN: ${TOKEN_GEMMA}
    container_name: peci_backend
    restart: unless-stopped
    env_file:
      - backend/backend/app/.env
      - ai_engine/keys.env
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ai_uploads:/app/ai_engine/uploads
      - ai_chroma:/app/ai_engine/chroma_db
    networks:
      peci_network:
        ipv4_address: 172.20.0.20

  #Frontend
  frontend:
    build:
      context: web
      dockerfile: Dockerfile
    container_name: peci_frontend
    restart: unless-stopped
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      peci_network:
        ipv4_address: 172.20.0.30

volumes:
  postgres_data:
  ai_uploads:
  ai_chroma:
